### ISSUE TITLE
REST API Endpoints for exporting / integrating into a already existing system

### ISSUE THREAD

**Issue by pascalboehler** [BHH-IT-Jahrgang2022/Pb2ITECHBotCH2LLG#1]
Must have requirement. Rest API is a possibility

**Comment by LazaroAlpaka** [comment]
Tutorial REST with Go: https://go.dev/doc/tutorial/web-service-gin

**Comment by LazaroAlpaka** [comment]
Connecting DB with API: https://dev.to/janirefdez/connect-rest-api-to-database-with-go-d8m

**Comment by LazaroAlpaka** [comment]
Serializer: https://pkg.go.dev/github.com/hyperledger/fabric-contract-api-go/serializer

**Comment by LazaroAlpaka** [comment]
Deserialize: https://dev.to/andyhaskell/build-a-web-api-client-in-go-part-2-deserializing-the-data-3p7

**Comment by RHOFF-Stud** [comment]
Redundant through Microservice Architecture
