### ISSUE TITLE
REST API for Frontend Applications

### ISSUE THREAD

**Issue by pascalboehler** [BHH-IT-Jahrgang2022/Pb2ITECHBotCH2LLG#12]
Create a REST Style API for integration of third party / first party apps

**Comment by RHOFF-Stud** [comment]
Endpoints:
- [ ] \connect - GET
- IN: -
- OUT: session_key
- [ ] \chat - GET
- IN: session_key, text
- OUT: session_key, response

**Comment by RHOFF-Stud** [comment]
- [x] ToDo: Send logs to Logging server

**Comment by RHOFF-Stud** [comment]
Resolved in latest pull - Logging Outstanding
