### ISSUE TITLE
Logging into a database

### ISSUE THREAD

**Issue by pascalboehler** [BHH-IT-Jahrgang2022/Pb2ITECHBotCH2LLG#2]
Log all questions the bot cannot handle into a database

**Comment by LazaroAlpaka** [comment]
DB integration example: https://go.dev/doc/tutorial/database-access

**Comment by LazaroAlpaka** [comment]
DB -> API connect: https://dev.to/janirefdez/connect-rest-api-to-database-with-go-d8m

**Comment by RHOFF-Stud** [comment]
ToDo:
- [x] integrate the logger into all other microservices

**Comment by RHOFF-Stud** [comment]
Implemented in last pull request
